import Waranasi from '../assets/Waranasi.jpg'
import Kashmir from "../assets/Kashmir.jpg";
import Keral from "../assets/Keral.jpg";
import Seoul from "../assets/Seoul5.jpg";
import Goa from "../assets/Goa.jpg";
import NewYork from "../assets/india.jpg";
import mumbai from "../assets/Mumbai.jpg";
import russia from "../assets/Russia.jpg";
import usa from "../assets/USA.jpg";
import madrid from "../assets/Seoul2.jpg";
import pune from "../assets/pune.jpg";

 const toursdata = [
   {
     id: 1,
     type: "spiritual",
     name: "Waranasi: City Of God",
     img: Waranasi,
     price: "$900",
     rating: "9.7",
     review: "Excellent",
     desc: "One of the oldest cities in the world, known for its spiritual significance",
     author: "@kshay Kathwate ",
   },
   {
     id: 2,
     type: "scenic",
     name: "Kashmir",
     img: Kashmir,
     price: "$1255",
     rating: "9.0",
     review: "Excellent",
     desc: "The 'Paradise on Earth' with breathtaking landscapes and serene lakes.",
     author: "@kshay Kathwate ",
   },
   {
     id: 3,
     type: "relaxing",
     name: "Kerala",
     img: Keral,
     price: "$1000",
     rating: "8.2",
     review: "Good",
     desc: "God's Own Country with serene backwaters and lush green landscapes.",
     author: "@kshay Kathwate ",
   },
   {
     id: 4,
     type: "modern",
     name: "Dream City Seoul",
     img: Seoul,
     price: "$1155",
     rating: "6.5",
     review: "Good",
     desc: "The dynamic capital of South Korea, blending modern and traditional elements.",
     author: "@kshay Kathwate ",
   },
   {
     id: 5,
     type: "beach",
     name: "Goa",
     img: Goa,
     price: "$805",
     rating: "6.5",
     review: "Good",
     desc: "The dynamic capital of South Korea, blending modern and traditional elements.",
     author: "@kshay Kathwate ",
   },
   {
     id: 6,
     type: "scenic",
     name: "New York",
     img: NewYork,
     price: "$800",
     rating: "8.5",
     review: "Good",
     desc: "New York City has been called fintech center and the most economically powerful city in the world.",
     author: "@kshay Kathwate ",
   },
   {
     id: 7,
     type: "scenic",
     name: "Mumbai",
     img: mumbai,
     price: "$600",
     rating: "8.5",
     review: "Excellent",
     desc: "Mumbai is famous for large markets, mesmerising beaches, towering buildings, & five-star hotels.",
     author: "@kshay Kathwate ",
   },
   {
     id: 8,
     type: "scenic",
     name: "Madrid",
     img: madrid,
     price: "$805",
     rating: "6.5",
     review: "Good",
     desc: "The dynamic capital of South Korea, blending modern and traditional elements.",
     author: "@kshay Kathwate ",
   },
   {
     id: 9,
     type: "scenic",
     name: "USA",
     img: usa,
     price: "$805",
     rating: "9.5",
     review: "Good",
     desc: "The United States of America (USA), commonly known as the United States (U.S.).",
     author: "@kshay Kathwate ",
   },
   {
     id: 10,
     type: "scenic",
     name: "Russia",
     img: russia,
     price: "$600",
     rating: "7.5",
     review: "Good",
     desc: "Russia or the Russian Federation, is a country spanning Eastern Europe and Northern Asia.",
     author: "@kshay Kathwate ",
   },
   {
     id: 11,
     type: "scenic",
     name: "Pune",
     img: pune,
     price: "$600",
     rating: "7.5",
     review: "Good ",
     desc: "Pune is a city in Maharashtra. It was once the base of the Peshwas (prime ministers) of the Maratha Empire",
     author: "@kshay Kathwate ",
   },
 ];
export default toursdata;